Core2Identity/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core2Identity.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Core2Identity.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class AdminController : Controller
    {
        private UserManager<ApplicationUser> _userManager;
        private IPasswordValidator<ApplicationUser> _passwordValidator;
        private IPasswordHasher<ApplicationUser> _passwordHasher;

        public AdminController(UserManager<ApplicationUser> userManager, IPasswordValidator<ApplicationUser> passwordValidator, IPasswordHasher<ApplicationUser> passwordHasher)
        {
            _userManager = userManager;
            _passwordValidator = passwordValidator;
            _passwordHasher = passwordHasher;
        }

        public IActionResult Index()
        {
            return View(_userManager.Users);
        }

        //Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RegisterModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser user = new ApplicationUser();
                user.UserName = model.UserName;
                user.Email = model.Email;

                var result = await _userManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    //Kayıt olan kullanıcı için default olarak User rolü atanıyor.
                    await _userManager.AddToRoleAsync(user, "User");
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }

            }
            return View(model);
        }

        //Delete
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                return View(user);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(string Id)
        {
            var user = await _userManager.FindByIdAsync(Id);

            if (user != null)
            {
                var result = await _userManager.DeleteAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "User not found.");
            }
            return View("Index", _userManager.Users);
        }

        //Edit
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                return View(user);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string id, string password, string Email)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                user.Email = Email;
                IdentityResult validPassword = null;

                if (!string.IsNullOrEmpty(password))
                {
                    validPassword = await _passwordValidator.ValidateAsync(_userManager, user, password);

                    if (validPassword.Succeeded)
                    {
                        user.PasswordHash = _passwordHasher.HashPassword(user, password);
                    }
                    else
                    {
                        foreach (var item in validPassword.Errors)
                        {
                            ModelState.AddModelError("", item.Description);
                        }
                    }
                }
                if (validPassword.Succeeded)
                {
                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var item in result.Errors)
                        {
                            ModelState.AddModelError("", item.Description);
                        }
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "User Not Found.");
            }
            return View(user);
        }
    }
}

Core2Identity/Controllers/AdminRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Core2Identity.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Core2Identity.Controllers
{
    public class AdminRoleController : Controller
    {
        private RoleManager<IdentityRole> _roleManager;
        private UserManager<ApplicationUser> _userManager;

        public AdminRoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            return View(_roleManager.Roles);
        }

        //Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (ModelState.IsValid)
            {
                var result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }

                }
            }
            return View(name);
        }

        //Role Düzenleme (Kullanıcılara Rol atama Rol Silme)
        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            var members = new List<ApplicationUser>();
            var nonMembers = new List<ApplicationUser>();

            foreach (var user in _userManager.Users)
            {
                var list = await _userManager.IsInRoleAsync(user, role.Name)
                    ? members : nonMembers;
                list.Add(user);
            }

            var model = new RoleDetails()
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoleEditModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (var userId in model.IdsToAdd ?? new string[] { })
                {
                    var user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);

                        if (!result.Succeeded)
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                }
                foreach (var userId in model.IdsToDelete ?? new string[] { })
                {
                    var user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);

                        if (!result.Succeeded)
                        {
                            foreach (var error in result.Errors)
                            {
                                ModelState.AddModelError("", error.Description);
                            }
                        }
                    }
                }

            }
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Edit", model.RoleId);
            }
        }

        //Delete
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                var result = await _roleManager.DeleteAsync(role);
                if (result.Succeeded)
                {
                    TempData["Message"] = $"{role.Name} has been deleted.";
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                }

            }
            else
            {
                ModelState.AddModelError("", "Role Not Found !");
            }
            return RedirectToAction("Index");
        }


    }
}

Core2Identity/Views/AdminRole/Create.cshtml
@model string
@{
    ViewData["Title"] = "Create";
}
<div class="bg-primary text-white p-1 m-1">
    <h2>Create Role</h2>
</div>
<form class="m-1 p-1" asp-action="Create" method="post">
    <div class="text-danger" asp-validation-summary="All"></div>
    <div class="form-group">
        <label for="name">Role Name</label>
        <input name="name" class="form-control" />
    </div>
    <input type="submit" class="btn btn-success" value="Create" />
    <a asp-action="Index" class="btn btn-danger">Cancel</a>
</form>

Core2Identity/Views/AdminRole/Edit.cshtml
@model RoleDetails
@{
    ViewData["Title"] = "Edit";
}

<div class="bg-primary text-white p-1 m-1">
    <h2>Edit Role</h2>
</div>
<div class="text-danger" asp-validation-summary="ModelOnly"></div>

<form asp-action="Edit" method="post">
    <input hidden="hidden" name="RoleId" value="@Model.Role.Id" />
    <input hidden="hidden" name="RoleName" value="@Model.Role.Name" />
    <h6 class="bg-info p-1 text-white">
        Add to @Model.Role.Name
    </h6>
    <table class="table table-bordered table-sm">
        @if (Model.NonMembers.Count() == 0)
        {
            <tr><td colspan="2">All Users are Members.</td></tr>
        }
        else
        {
            @foreach (var user in Model.NonMembers)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td><input type="checkbox" name="IdsToAdd" value="@user.Id" /></td>
                </tr>
            }

        }
    </table>

    <h6 class="bg-info p-1 text-white">
        Delete to @Model.Role.Name
    </h6>
    <table class="table table-bordered table-sm">
        @if (Model.Members.Count() == 0)
        {
            <tr><td colspan="2">No Users are Members.</td></tr>
        }
        else
        {
            @foreach (var user in Model.Members)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td><input type="checkbox" name="IdsToDelete" value="@user.Id" /></td>
                </tr>
            }

        }
    </table>
    <button type="submit" class="btn btn-info" >Save</button>
    <a asp-action="Index" class="btn btn-danger">Cancel</a>
</form>

Core2Identity/Views/AdminRole/Index.cshtml
@model IEnumerable<IdentityRole>
@{
    ViewData["Title"] = "Index";
}

<div class="bg-primary text-white p-1 m-1">
    <h2>Role List</h2>
</div>

@*Key'i olmayan hata mesajlarını yazar. Yani model(ApplicationUser) seviyesinde hata mesajları.*@
<div class="text-danger" asp-validation-summary="ModelOnly"></div>
@if (TempData["Message"] != null)
{
    <div class="alert alert-success">
        @TempData["Message"]
    </div>
}
<table class="table table-bordered table-striped table-sm m-1 p-1">
    <tr>
        <th>Role Id</th>
        <th>Role Name</th>
        <th>Users</th>
        <th>Transaction</th>
        <th>Transaction</th>
    </tr>
    @if (Model.Count() == 0)
    {
        <tr>
            <td colspan="4" class="text-center">No Roles.</td>

        </tr>
    }
    else
    {
        foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td identity-role="@item.Id"></td>
                <td>
                    <form asp-route-id="@item.Id" asp-action="Delete" method="post">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
                <td>
                    <a asp-controller="AdminRole"
                       asp-action="Edit"
                       asp-route-id="@item.Id"
                       class="btn btn-info">
                        Edit
                    </a>
                </td>
                @*  ****** Bir onay sayfasına gönderip oradan sildirmek için yazdım.
                        <td>
                        <a
                           asp-action="Delete"
                           asp-controller="Admin"
                           asp-route-id="@item.Id"
                           class="btn btn-danger">Delete</a>
                    </td> ***** *@
            </tr>
        }
    }
    <tr></tr>
</table>

<a asp-action="Create" class="btn btn-success">
    Create Role
</a>